### ISSUE TITLE
Remove leftover on exercise 05-executing

### ISSUE THREAD

**Issue by lucapari** [eficode-academy/docker-katas#143]
On exercise `05-executing` there's a[ typo on the summary](https://github.com/eficode-academy/docker-katas/blob/master/labs/05-executing.md?plain=1#L37). The summary says that we have seen `terminating any of the the process by Ctrl+d that does not have PID 1`, but there's no evidence of this in any part of the exercise. Probably some leftover due to more recent changes to the file.

**Comment by sofusalbertsen** [comment]
Thanks @lucapari !
Will look into it, and thanks for using our exercises 🥇

**Comment by sofusalbertsen** [comment]
Have changed the wording.
